import { Demo } from "./BCTabs";

export const tob_base_open: Demo[] = [
  {
    label: "Flutter Android",
    icon: "/fonts/flutter_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.xcxwo.com/app/qrcode/OpenIM-Flutter-B",
    hover: false,
    download: "https://www.xcxwo.com/OpenIM-Flutter-B",
    type: "mobile",
  },
  {
    label: "Flutter IOS",
    icon: "/fonts/native_ios.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "/fonts/flutter_ios_qrcode_b.png",
    hover: false,
    download: "https://testflight.apple.com/join/GIWC3qSV",
    type: "mobile",
  },
  {
    label: "Native Android",
    icon: "/fonts/native_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.xcxwo.com/app/qrcode/IM-NBB",
    hover: false,
    download: "https://www.xcxwo.com/IM-NBB",
    type: "mobile",
  },
  {
    label: "Native IOS",
    icon: "/fonts/native_ios.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "/fonts/native_ios_qrcode_b.png",
    hover: false,
    download: "https://testflight.apple.com/join/lQyAMpq4",
    type: "mobile",
  },
  {
    label: "uni-app Android",
    icon: "/fonts/native_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.xcxwo.com/app/qrcode/IM-UBB",
    hover: false,
    download: "https://www.xcxwo.com/IM-UBB",
    type: "mobile",
  },
  {
    label: "Pc Web ToC",
    icon: "/fonts/pc_web_toc.png",
    top_right_icon: "",
    hover: false,
    download: "https://web-tob.rentsoft.cn/",
  },
  {
    label: "Electron for Mac",
    icon: "/fonts/electron_for_mac.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download: "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-BB-1.0.0.dmg",
  },
  {
    label: "Electron for Mac M1",
    icon: "/fonts/electron_for_mac.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-BB-1.0.0-arm64.dmg",
  },
  {
    label: "Electron for Windows",
    icon: "/fonts/electron_for_windows.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-BB%20Setup%201.0.0.exe",
  },
  {
    label: "Electron for Ubuntu/UOS/Kylinos",
    icon: "/fonts/electron_for_linux.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-BB_1.0.0_amd64.deb",
  },
  {
    label: "Electron for Ubuntu/UOS/Kylinos arm64",
    icon: "/fonts/electron_for_linux.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-BB_1.0.0_arm64.deb",
  },
];
export const tob_enterprise: Demo[] = [
  {
    label: "Flutter",
    icon: "/fonts/flutter_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.xcxwo.com/app/qrcode/IM-FBER",
    hover: false,
    download: "https://www.pgyer.com/IM-FBER",
    type: "mobile",
  },
  // {
  //   label: "Flutter IOS",
  //   icon: "/fonts/native_ios.png",
  //   top_right_icon: "/fonts/qrcode.png",
  //   qrcode: "/fonts/flutter_ios_qrcode_b_e.png",
  //   hover: false,
  //   download: "https://testflight.apple.com/join/39xhz65U",
  //   type: "mobile",
  // },
  // {
  //   label: "Native Android",
  //   icon: "/fonts/native_android.png",
  //   top_right_icon: "/fonts/qrcode.png",
  //   qrcode: "https://www.xcxwo.com/app/qrcode/IM-NBER",
  //   hover: false,
  //   download: "https://www.xcxwo.com/IM-NBER",
  //   type: "mobile",
  // },
  // {
  //   label: "Native IOS",
  //   icon: "/fonts/native_ios.png",
  //   top_right_icon: "/fonts/qrcode.png",
  //   qrcode: "/fonts/native_ios_qrcode_b_e.png",
  //   hover: false,
  //   download: "https://testflight.apple.com/join/gOuBlFbw",
  //   type: "mobile",
  // },
  {
    label: "uni-app Android",
    icon: "/fonts/native_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.xcxwo.com/app/qrcode/IM-UBER",
    hover: false,
    download: "https://www.xcxwo.com/IM-UBER",
    type: "mobile",
    only_cn: true,
  },
  {
    label: "Pc Web",
    icon: "/fonts/pc_web_toc.png",
    top_right_icon: "",
    hover: false,
    download: "https://web-enterprise-tob.rentsoft.cn",
  },
  {
    label: "Electron for Mac",
    icon: "/fonts/electron_for_mac.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-BER_3.5.1_x64.dmg",
  },
  {
    label: "Electron for Mac M1",
    icon: "/fonts/electron_for_mac.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-BER_3.5.1_arm64.dmg",
  },
  {
    label: "Electron for Windows",
    icon: "/fonts/electron_for_windows.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download: "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-BER_3.5.1.exe",
  },
  {
    label: "Electron for Ubuntu/UOS/Kylinos",
    icon: "/fonts/electron_for_linux.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-BER_3.5.1_amd64.deb",
    only_cn: true,
  },
  {
    label: "Electron for Ubuntu/UOS/Kylinos arm64",
    icon: "/fonts/electron_for_linux.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-BER_3.5.1_arm64.deb",
    only_cn: true,
  },
];
