import { Demo } from "./BCTabs";

export const toc_base_open: Demo[] = [
  {
    label: "Flutter Android",
    icon: "/fonts/flutter_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.xcxwo.com/app/qrcode/OpenIM-Flutter",
    hover: false,
    download: "https://www.xcxwo.com/OpenIM-Flutter",
    type: "mobile",
  },
  {
    label: "Flutter IOS",
    icon: "/fonts/native_ios.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "/fonts/flutter_ios_qrcode.png",
    hover: false,
    download: "https://testflight.apple.com/join/UIWackuX",
    type: "mobile",
  },
  {
    label: "Native Android",
    icon: "/fonts/native_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.xcxwo.com/app/qrcode/OpenIM-android",
    hover: false,
    download: "https://www.xcxwo.com/OpenIM-android",
    type: "mobile",
  },
  {
    label: "Native IOS",
    icon: "/fonts/native_ios.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "/fonts/native_ios_qrcode.png",
    hover: false,
    download: "https://testflight.apple.com/join/hRrwpm38",
    type: "mobile",
  },
  {
    label: "uni-app Android",
    icon: "/fonts/native_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.xcxwo.com/app/qrcode/IM-UCB",
    hover: false,
    download: "https://www.xcxwo.com/IM-UCB",
    type: "mobile",
  },
  {
    label: "Pc Web ToC",
    icon: "/fonts/pc_web_toc.png",
    top_right_icon: "",
    hover: false,
    download: "https://web.rentsoft.cn/",
  },
  {
    label: "Electron for Mac",
    icon: "/fonts/electron_for_mac.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download: "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-CB-3.3.0.dmg",
  },
  {
    label: "Electron for Mac M1",
    icon: "/fonts/electron_for_mac.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-CB-3.3.0-arm64.dmg",
  },
  {
    label: "Electron for Windows",
    icon: "/fonts/electron_for_windows.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-CB%20Setup%203.3.0.exe",
  },
  {
    label: "Electron for Ubuntu/UOS/Kylinos",
    icon: "/fonts/electron_for_linux.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-CB_3.3.0_amd64.deb",
  },
  {
    label: "Electron for Ubuntu/UOS/Kylinos arm64",
    icon: "/fonts/electron_for_linux.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenIM-CB_3.3.0_arm64.deb",
  },
];
export const toc_enterprise: Demo[] = [
  {
    label: "Flutter",
    icon: "/fonts/flutter_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.pgyer.com/app/qrcode/IM-FCER",
    hover: false,
    download: "https://www.pgyer.com/IM-FCER",
    type: "mobile",
  },
  // {
  //   label: "Flutter IOS",
  //   icon: "/fonts/native_ios.png",
  //   top_right_icon: "/fonts/qrcode.png",
  //   qrcode: "/fonts/flutter_ios_qrcode_c_e.png",
  //   hover: false,
  //   download: "https://testflight.apple.com/join/Wl0C7dvP",
  //   type: "mobile",
  // },
  {
    label: "Native",
    icon: "/fonts/native_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.xcxwo.com/app/qrcode/OpenIM-Enterprise",
    hover: false,
    download: "https://www.xcxwo.com/OpenIM-Enterprise",
    type: "mobile",
  },
  // {
  //   label: "Native IOS",
  //   icon: "/fonts/native_ios.png",
  //   top_right_icon: "/fonts/qrcode.png",
  //   qrcode: "/fonts/native_ios_qrcode_c_e.png",
  //   hover: false,
  //   download: "https://testflight.apple.com/join/cGuG9pVg",
  //   type: "mobile",
  // },
  {
    label: "uni-app Android",
    icon: "/fonts/native_android.png",
    top_right_icon: "/fonts/qrcode.png",
    qrcode: "https://www.xcxwo.com/app/qrcode/IM-UCER",
    hover: false,
    download: "https://www.xcxwo.com/IM-UCER",
    type: "mobile",
    only_cn: true,
  },
  {
    label: "H5",
    icon: "/fonts/pc_web_toc.png",
    top_right_icon: "",
    hover: false,
    download: "https://h5-enterprise.rentsoft.cn/",
  },
  {
    label: "Pc Web",
    icon: "/fonts/pc_web_toc.png",
    top_right_icon: "",
    hover: false,
    download: "https://web-enterprise.rentsoft.cn/",
  },
  {
    label: "Electron for Mac",
    icon: "/fonts/electron_for_mac.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenCorp-CER_3.8.1_x64.dmg",
  },
  {
    label: "Electron for Mac M1",
    icon: "/fonts/electron_for_mac.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenCorp-CER_3.8.1_arm64.dmg",
  },
  {
    label: "Electron for Windows",
    icon: "/fonts/electron_for_windows.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenCorp-CER_3.8.1.exe",
  },
  {
    label: "Electron for Ubuntu/UOS/Kylinos",
    icon: "/fonts/electron_for_linux.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenCorp-CER_3.8.1_amd64.deb",
    only_cn: true,
  },
  {
    label: "Electron for Ubuntu/UOS/Kylinos arm64",
    icon: "/fonts/electron_for_linux.png",
    top_right_icon: "/fonts/download.png",
    type: "pc",
    hover: false,
    download:
      "https://app-1302656840.cos.ap-nanjing.myqcloud.com/OpenCorp-CER_3.8.1_arm64.deb",
    only_cn: true,
  },
];
